import type { Metadata } from "next";
import "./globals.css";
import { inter, roboto, montserrat } from '@/app/components/fonts'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${roboto.variable} ${montserrat.variable}`}>
      <body className={roboto.className}>
        {children}
      </body>
    </html>
  );
}
